// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"time"
)

type ChatMessage struct {
	ID        string          `json:"id"`
	Role      string          `json:"role"`
	Content   string          `json:"content"`
	DocRefs   []string        `json:"docRefs"`
	ToolName  *string         `json:"toolName,omitempty"`
	ToolInput *string         `json:"toolInput,omitempty"`
	ToolMeta  *ToolResultMeta `json:"toolMeta,omitempty"`
	CreatedAt time.Time       `json:"createdAt"`
}

type Conversation struct {
	ID        string         `json:"id"`
	VaultID   string         `json:"vaultId"`
	Title     string         `json:"title"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
	Messages  []*ChatMessage `json:"messages"`
}

type Mutation struct {
}

type Query struct {
}

type ToolDocRef struct {
	Title string  `json:"title"`
	Path  string  `json:"path"`
	Score float64 `json:"score"`
}

type ToolResultMeta struct {
	DurationMs     int           `json:"durationMs"`
	ResultCount    *int          `json:"resultCount,omitempty"`
	ChunkCount     *int          `json:"chunkCount,omitempty"`
	MatchedDocs    []*ToolDocRef `json:"matchedDocs,omitempty"`
	DocumentPath   *string       `json:"documentPath,omitempty"`
	DocumentTitle  *string       `json:"documentTitle,omitempty"`
	ContentLength  *int          `json:"contentLength,omitempty"`
	WebResultCount *int          `json:"webResultCount,omitempty"`
	WebSources     []*ToolWebRef `json:"webSources,omitempty"`
}

type ToolWebRef struct {
	Title string `json:"title"`
	URL   string `json:"url"`
}
