// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"time"
)

type ChatMessage struct {
	ID         string          `json:"id"`
	Role       string          `json:"role"`
	Content    string          `json:"content"`
	DocRefs    []string        `json:"docRefs"`
	ToolName   *string         `json:"toolName,omitempty"`
	ToolInput  *string         `json:"toolInput,omitempty"`
	ToolMeta   *ToolResultMeta `json:"toolMeta,omitempty"`
	ToolCallID *string         `json:"toolCallId,omitempty"`
	ToolCalls  *string         `json:"toolCalls,omitempty"`
	CreatedAt  time.Time       `json:"createdAt"`
}

type Conversation struct {
	ID        string         `json:"id"`
	VaultID   string         `json:"vaultId"`
	Title     string         `json:"title"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
	Messages  []*ChatMessage `json:"messages"`
}

type DiffResult struct {
	Hunks []*DiffHunk `json:"hunks"`
	Stats *DiffStats  `json:"stats"`
}

type Mutation struct {
}

type Query struct {
}

type ShareLink struct {
	ID        string     `json:"id"`
	VaultID   string     `json:"vaultId"`
	Path      string     `json:"path"`
	IsFolder  bool       `json:"isFolder"`
	Token     *string    `json:"token,omitempty"`
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	CreatedAt time.Time  `json:"createdAt"`
}

type ToolDocRef struct {
	Title string  `json:"title"`
	Path  string  `json:"path"`
	Score float64 `json:"score"`
}

type ToolResultMeta struct {
	DurationMs     int           `json:"durationMs"`
	ResultCount    *int          `json:"resultCount,omitempty"`
	ChunkCount     *int          `json:"chunkCount,omitempty"`
	MatchedDocs    []*ToolDocRef `json:"matchedDocs,omitempty"`
	DocumentPath   *string       `json:"documentPath,omitempty"`
	DocumentTitle  *string       `json:"documentTitle,omitempty"`
	ContentLength  *int          `json:"contentLength,omitempty"`
	WebResultCount *int          `json:"webResultCount,omitempty"`
	WebSources     []*ToolWebRef `json:"webSources,omitempty"`
}

type ToolWebRef struct {
	Title string `json:"title"`
	URL   string `json:"url"`
}

type VaultMember struct {
	UserID    string    `json:"userId"`
	UserName  string    `json:"userName"`
	VaultID   string    `json:"vaultId"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"createdAt"`
}

type VaultRole struct {
	VaultID string `json:"vaultId"`
	Role    string `json:"role"`
}
