package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"fmt"
	"log/slog"
	"time"

	"github.com/raphi011/knowhow/internal/auth"
	"github.com/raphi011/knowhow/internal/db"
	"github.com/raphi011/knowhow/internal/diff"
	"github.com/raphi011/knowhow/internal/models"
	"github.com/raphi011/knowhow/internal/parser"
	"github.com/raphi011/knowhow/internal/search"
)

// WikiLinks is the resolver for the wikiLinks field.
func (r *documentResolver) WikiLinks(ctx context.Context, obj *Document) ([]*WikiLink, error) {
	links, err := r.db.GetWikiLinks(ctx, obj.ID)
	if err != nil {
		return nil, err
	}
	result := make([]*WikiLink, len(links))
	for i := range links {
		result[i] = wikiLinkToGraphQL(&links[i])
	}
	return result, nil
}

// Backlinks is the resolver for the backlinks field.
func (r *documentResolver) Backlinks(ctx context.Context, obj *Document) ([]*WikiLink, error) {
	links, err := r.db.GetBacklinks(ctx, obj.ID)
	if err != nil {
		return nil, err
	}
	result := make([]*WikiLink, len(links))
	for i := range links {
		result[i] = wikiLinkToGraphQL(&links[i])
	}
	return result, nil
}

// Relations is the resolver for the relations field.
func (r *documentResolver) Relations(ctx context.Context, obj *Document) ([]*DocRelation, error) {
	relations, err := r.db.GetRelations(ctx, obj.ID)
	if err != nil {
		return nil, err
	}
	result := make([]*DocRelation, len(relations))
	for i := range relations {
		result[i] = relationToGraphQL(&relations[i])
	}
	return result, nil
}

// QueryBlocks is the resolver for the queryBlocks field.
func (r *documentResolver) QueryBlocks(ctx context.Context, obj *Document) ([]*QueryBlock, error) {
	parsed := parser.ExtractQueryBlocks(obj.Content)
	if len(parsed) == 0 {
		return []*QueryBlock{}, nil
	}

	results := make([]*QueryBlock, len(parsed))
	for i, p := range parsed {
		block := resolveQueryBlock(ctx, r.db, obj.VaultID, p)
		results[i] = &block
	}
	return results, nil
}

// Versions is the resolver for the versions field.
func (r *documentResolver) Versions(ctx context.Context, obj *Document, limit *int, offset *int) (*DocumentVersionConnection, error) {
	l, o := 20, 0
	if limit != nil {
		l = *limit
	}
	if offset != nil {
		o = *offset
	}
	versions, err := r.db.ListVersions(ctx, obj.ID, l, o)
	if err != nil {
		return nil, fmt.Errorf("list versions: %w", err)
	}
	count, err := r.db.CountVersions(ctx, obj.ID)
	if err != nil {
		return nil, fmt.Errorf("count versions: %w", err)
	}
	gqlVersions := make([]*DocumentVersion, len(versions))
	for i := range versions {
		gqlVersions[i] = versionToGraphQL(&versions[i])
	}
	return &DocumentVersionConnection{
		Versions:   gqlVersions,
		TotalCount: count,
	}, nil
}

// VaultRoles is the resolver for the vaultRoles field.
func (r *meResolver) VaultRoles(ctx context.Context, obj *Me) ([]*VaultRole, error) {
	ac, err := auth.FromContext(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*VaultRole, len(ac.Vaults))
	for i, vp := range ac.Vaults {
		result[i] = &VaultRole{
			VaultID: vp.VaultID,
			Role:    string(vp.Role),
		}
	}
	return result, nil
}

// CreateVault is the resolver for the createVault field.
func (r *mutationResolver) CreateVault(ctx context.Context, input VaultInput) (*Vault, error) {
	ac, err := auth.FromContext(ctx)
	if err != nil {
		return nil, err
	}
	v, err := r.vaultService.Create(ctx, ac.UserID, models.VaultInput{
		Name:        input.Name,
		Description: input.Description,
	})
	if err != nil {
		return nil, err
	}
	return vaultToGraphQL(v), nil
}

// DeleteVault is the resolver for the deleteVault field.
func (r *mutationResolver) DeleteVault(ctx context.Context, id string) (bool, error) {
	if err := auth.RequireVaultRole(ctx, id, models.RoleAdmin); err != nil {
		return false, err
	}
	if err := r.vaultService.Delete(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// CreateDocument is the resolver for the createDocument field.
func (r *mutationResolver) CreateDocument(ctx context.Context, vaultID string, file FileInput, source *string) (*Document, error) {
	if err := auth.RequireVaultRole(ctx, vaultID, models.RoleWrite); err != nil {
		return nil, err
	}
	src := models.SourceManual
	if source != nil {
		src = models.DocumentSource(*source)
		if !src.Valid() {
			return nil, fmt.Errorf("invalid document source: %q", *source)
		}
	}
	doc, err := r.documentService.Create(ctx, models.DocumentInput{
		VaultID: vaultID,
		Path:    file.Path,
		Content: file.Content,
		Source:  src,
	})
	if err != nil {
		return nil, err
	}
	return documentToGraphQL(doc), nil
}

// UpdateDocument is the resolver for the updateDocument field.
func (r *mutationResolver) UpdateDocument(ctx context.Context, vaultID string, path string, content string) (*Document, error) {
	if err := auth.RequireVaultRole(ctx, vaultID, models.RoleWrite); err != nil {
		return nil, err
	}
	doc, err := r.documentService.Update(ctx, vaultID, path, content)
	if err != nil {
		return nil, err
	}
	return documentToGraphQL(doc), nil
}

// MoveDocument is the resolver for the moveDocument field.
func (r *mutationResolver) MoveDocument(ctx context.Context, vaultID string, oldPath string, newPath string) (*Document, error) {
	if err := auth.RequireVaultRole(ctx, vaultID, models.RoleWrite); err != nil {
		return nil, err
	}
	doc, err := r.documentService.Move(ctx, vaultID, oldPath, newPath)
	if err != nil {
		return nil, err
	}
	return documentToGraphQL(doc), nil
}

// DeleteDocument is the resolver for the deleteDocument field.
func (r *mutationResolver) DeleteDocument(ctx context.Context, vaultID string, path string) (bool, error) {
	if err := auth.RequireVaultRole(ctx, vaultID, models.RoleWrite); err != nil {
		return false, err
	}
	if err := r.documentService.Delete(ctx, vaultID, path); err != nil {
		return false, err
	}
	return true, nil
}

// DeleteDocumentsByPrefix is the resolver for the deleteDocumentsByPrefix field.
func (r *mutationResolver) DeleteDocumentsByPrefix(ctx context.Context, vaultID string, pathPrefix string) (int, error) {
	if err := auth.RequireVaultRole(ctx, vaultID, models.RoleWrite); err != nil {
		return 0, err
	}
	return r.documentService.DeleteByPrefix(ctx, vaultID, pathPrefix)
}

// MoveDocumentsByPrefix is the resolver for the moveDocumentsByPrefix field.
func (r *mutationResolver) MoveDocumentsByPrefix(ctx context.Context, vaultID string, oldPrefix string, newPrefix string) (int, error) {
	if err := auth.RequireVaultRole(ctx, vaultID, models.RoleWrite); err != nil {
		return 0, err
	}
	return r.documentService.MoveByPrefix(ctx, vaultID, oldPrefix, newPrefix)
}

// CreateRelation is the resolver for the createRelation field.
func (r *mutationResolver) CreateRelation(ctx context.Context, input RelationInput) (*DocRelation, error) {
	// Verify access to both documents' vaults
	fromDoc, err := r.db.GetDocumentByID(ctx, input.FromDocID)
	if err != nil {
		return nil, fmt.Errorf("get from document: %w", err)
	}
	if fromDoc == nil {
		return nil, fmt.Errorf("from document not found: %s", input.FromDocID)
	}
	fromVaultID, err := models.RecordIDString(fromDoc.Vault)
	if err != nil {
		return nil, fmt.Errorf("extract from document vault ID: %w", err)
	}
	if err := auth.RequireVaultRole(ctx, fromVaultID, models.RoleWrite); err != nil {
		return nil, err
	}

	toDoc, err := r.db.GetDocumentByID(ctx, input.ToDocID)
	if err != nil {
		return nil, fmt.Errorf("get to document: %w", err)
	}
	if toDoc == nil {
		return nil, fmt.Errorf("to document not found: %s", input.ToDocID)
	}
	toVaultID, err := models.RecordIDString(toDoc.Vault)
	if err != nil {
		return nil, fmt.Errorf("extract to document vault ID: %w", err)
	}
	if err := auth.RequireVaultRole(ctx, toVaultID, models.RoleRead); err != nil {
		return nil, err
	}

	rel, err := r.db.CreateRelation(ctx, models.DocRelationInput{
		FromDocID: input.FromDocID,
		ToDocID:   input.ToDocID,
		RelType:   input.RelType,
		Source:    string(models.RelSourceAPI),
	})
	if err != nil {
		return nil, err
	}
	return relationToGraphQL(rel), nil
}

// DeleteRelation is the resolver for the deleteRelation field.
func (r *mutationResolver) DeleteRelation(ctx context.Context, id string) (bool, error) {
	// Look up the relation to verify vault access on both documents
	relations, err := r.db.GetRelationByID(ctx, id)
	if err != nil {
		return false, fmt.Errorf("get relation: %w", err)
	}
	if relations == nil {
		return false, fmt.Errorf("relation not found: %s", id)
	}
	inDocID, err := models.RecordIDString(relations.In)
	if err != nil {
		return false, fmt.Errorf("extract relation in doc ID: %w", err)
	}
	inDoc, err := r.db.GetDocumentByID(ctx, inDocID)
	if err != nil {
		return false, fmt.Errorf("get in document: %w", err)
	}
	if inDoc != nil {
		vaultID, err := models.RecordIDString(inDoc.Vault)
		if err != nil {
			return false, fmt.Errorf("extract vault ID: %w", err)
		}
		if err := auth.RequireVaultRole(ctx, vaultID, models.RoleWrite); err != nil {
			return false, err
		}
	}

	if err := r.db.DeleteRelation(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// CreateTemplate is the resolver for the createTemplate field.
func (r *mutationResolver) CreateTemplate(ctx context.Context, input TemplateInput) (*Template, error) {
	if input.VaultID != nil {
		if err := auth.RequireVaultRole(ctx, *input.VaultID, models.RoleWrite); err != nil {
			return nil, err
		}
	}
	isAI := false
	if input.IsAITemplate != nil {
		isAI = *input.IsAITemplate
	}
	t, err := r.templateService.Create(ctx, models.TemplateInput{
		VaultID:      input.VaultID,
		Name:         input.Name,
		Description:  input.Description,
		Content:      input.Content,
		IsAITemplate: isAI,
	})
	if err != nil {
		return nil, err
	}
	return templateToGraphQL(t), nil
}

// DeleteTemplate is the resolver for the deleteTemplate field.
func (r *mutationResolver) DeleteTemplate(ctx context.Context, id string) (bool, error) {
	// Check vault access if the template is scoped to a vault
	tmpl, err := r.templateService.Get(ctx, id)
	if err != nil {
		return false, fmt.Errorf("get template: %w", err)
	}
	if tmpl == nil {
		return false, fmt.Errorf("template not found: %s", id)
	}
	if tmpl.Vault != nil {
		vaultID, err := models.RecordIDString(*tmpl.Vault)
		if err != nil {
			return false, fmt.Errorf("extract template vault ID: %w", err)
		}
		if err := auth.RequireVaultRole(ctx, vaultID, models.RoleWrite); err != nil {
			return false, err
		}
	}

	if err := r.templateService.Delete(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// CreateFolder is the resolver for the createFolder field.
func (r *mutationResolver) CreateFolder(ctx context.Context, vaultID string, path string) (*Folder, error) {
	if err := auth.RequireVaultRole(ctx, vaultID, models.RoleWrite); err != nil {
		return nil, err
	}
	folder, err := r.vaultService.CreateFolder(ctx, vaultID, path)
	if err != nil {
		return nil, err
	}
	f := folderToGraphQL(*folder)
	return &f, nil
}

// DeleteFolder is the resolver for the deleteFolder field.
func (r *mutationResolver) DeleteFolder(ctx context.Context, vaultID string, path string) (bool, error) {
	if err := auth.RequireVaultRole(ctx, vaultID, models.RoleWrite); err != nil {
		return false, err
	}
	if err := r.vaultService.DeleteFolder(ctx, vaultID, path); err != nil {
		return false, err
	}
	return true, nil
}

// MoveFolder is the resolver for the moveFolder field.
func (r *mutationResolver) MoveFolder(ctx context.Context, vaultID string, oldPath string, newPath string) (bool, error) {
	if err := auth.RequireVaultRole(ctx, vaultID, models.RoleWrite); err != nil {
		return false, err
	}
	if err := r.vaultService.MoveFolder(ctx, vaultID, oldPath, newPath); err != nil {
		return false, err
	}
	return true, nil
}

// CreateConversation is the resolver for the createConversation field.
func (r *mutationResolver) CreateConversation(ctx context.Context, vaultID string) (*Conversation, error) {
	if err := auth.RequireVaultRole(ctx, vaultID, models.RoleWrite); err != nil {
		return nil, err
	}
	ac, err := auth.FromContext(ctx)
	if err != nil {
		return nil, err
	}
	conv, err := r.db.CreateConversation(ctx, vaultID, ac.UserID)
	if err != nil {
		return nil, err
	}
	result := conversationToGraphQL(conv)
	result.Messages = []*ChatMessage{}
	return result, nil
}

// DeleteConversation is the resolver for the deleteConversation field.
func (r *mutationResolver) DeleteConversation(ctx context.Context, id string) (bool, error) {
	conv, err := r.db.GetConversation(ctx, id)
	if err != nil {
		return false, err
	}
	if conv == nil {
		return false, fmt.Errorf("conversation not found")
	}
	vaultID, err := models.RecordIDString(conv.Vault)
	if err != nil {
		return false, fmt.Errorf("extract vault ID: %w", err)
	}
	if err := auth.RequireVaultRole(ctx, vaultID, models.RoleWrite); err != nil {
		return false, err
	}
	if err := r.db.DeleteConversation(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// RenameConversation is the resolver for the renameConversation field.
func (r *mutationResolver) RenameConversation(ctx context.Context, id string, title string) (*Conversation, error) {
	conv, err := r.db.GetConversation(ctx, id)
	if err != nil {
		return nil, err
	}
	if conv == nil {
		return nil, fmt.Errorf("conversation not found")
	}
	vaultID, err := models.RecordIDString(conv.Vault)
	if err != nil {
		return nil, fmt.Errorf("extract vault ID: %w", err)
	}
	if err := auth.RequireVaultRole(ctx, vaultID, models.RoleWrite); err != nil {
		return nil, err
	}
	if err := r.db.UpdateConversationTitle(ctx, id, title); err != nil {
		return nil, err
	}
	updated, err := r.db.GetConversation(ctx, id)
	if err != nil {
		return nil, err
	}
	result := conversationToGraphQL(updated)
	result.Messages = []*ChatMessage{}
	return result, nil
}

// RollbackDocument is the resolver for the rollbackDocument field.
func (r *mutationResolver) RollbackDocument(ctx context.Context, vaultID string, documentID string, versionID string) (*Document, error) {
	if err := auth.RequireVaultRole(ctx, vaultID, models.RoleWrite); err != nil {
		return nil, err
	}
	doc, err := r.documentService.Rollback(ctx, vaultID, documentID, versionID)
	if err != nil {
		return nil, fmt.Errorf("rollback document: %w", err)
	}
	return documentToGraphQL(doc), nil
}

// AddVaultMember is the resolver for the addVaultMember field.
func (r *mutationResolver) AddVaultMember(ctx context.Context, vaultID string, userID string, role string) (*VaultMember, error) {
	if err := auth.RequireVaultRole(ctx, vaultID, models.RoleAdmin); err != nil {
		return nil, err
	}
	vaultRole := models.VaultRole(role)
	if !vaultRole.Valid() {
		return nil, fmt.Errorf("invalid role: %q", role)
	}
	member, err := r.db.CreateVaultMember(ctx, userID, vaultID, vaultRole)
	if err != nil {
		return nil, err
	}
	return vaultMemberToGraphQL(r.db, ctx, member)
}

// UpdateVaultMemberRole is the resolver for the updateVaultMemberRole field.
func (r *mutationResolver) UpdateVaultMemberRole(ctx context.Context, vaultID string, userID string, role string) (bool, error) {
	if err := auth.RequireVaultRole(ctx, vaultID, models.RoleAdmin); err != nil {
		return false, err
	}
	vaultRole := models.VaultRole(role)
	if !vaultRole.Valid() {
		return false, fmt.Errorf("invalid role: %q", role)
	}
	if err := r.db.UpdateVaultMemberRole(ctx, userID, vaultID, vaultRole); err != nil {
		return false, err
	}
	return true, nil
}

// RemoveVaultMember is the resolver for the removeVaultMember field.
func (r *mutationResolver) RemoveVaultMember(ctx context.Context, vaultID string, userID string) (bool, error) {
	if err := auth.RequireVaultRole(ctx, vaultID, models.RoleAdmin); err != nil {
		return false, err
	}
	if err := r.db.DeleteVaultMember(ctx, userID, vaultID); err != nil {
		return false, err
	}
	return true, nil
}

// CreateShareLink is the resolver for the createShareLink field.
func (r *mutationResolver) CreateShareLink(ctx context.Context, vaultID string, path string, isFolder bool, expiresAt *time.Time) (*ShareLink, error) {
	if err := auth.RequireVaultRole(ctx, vaultID, models.RoleAdmin); err != nil {
		return nil, err
	}
	ac, err := auth.FromContext(ctx)
	if err != nil {
		return nil, err
	}

	rawToken, tokenHash, err := auth.GenerateToken()
	if err != nil {
		return nil, fmt.Errorf("generate share token: %w", err)
	}

	var expiresAtStr *string
	if expiresAt != nil {
		s := expiresAt.Format(time.RFC3339)
		expiresAtStr = &s
	}

	link, err := r.db.CreateShareLink(ctx, vaultID, tokenHash, path, isFolder, ac.UserID, expiresAtStr)
	if err != nil {
		return nil, err
	}

	gql := shareLinkToGraphQL(link)
	gql.Token = &rawToken // return raw token only on creation
	return gql, nil
}

// DeleteShareLink is the resolver for the deleteShareLink field.
func (r *mutationResolver) DeleteShareLink(ctx context.Context, id string) (bool, error) {
	// Look up the share link to find its vault, then require admin on that vault.
	link, err := r.db.GetShareLink(ctx, id)
	if err != nil {
		return false, fmt.Errorf("get share link: %w", err)
	}
	if link == nil {
		return false, fmt.Errorf("share link not found: %s", id)
	}
	vaultID, err := models.RecordIDString(link.Vault)
	if err != nil {
		return false, fmt.Errorf("extract vault ID from share link: %w", err)
	}
	if err := auth.RequireVaultRole(ctx, vaultID, models.RoleAdmin); err != nil {
		return false, err
	}
	if err := r.db.DeleteShareLink(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, name string, email *string) (*User, error) {
	if err := auth.RequireSystemAdmin(ctx); err != nil {
		return nil, err
	}
	user, err := r.db.CreateUser(ctx, models.UserInput{
		Name:  name,
		Email: email,
	})
	if err != nil {
		return nil, err
	}
	return userToGraphQL(user), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*Me, error) {
	ac, err := auth.FromContext(ctx)
	if err != nil {
		return nil, err
	}
	user, err := r.db.GetUser(ctx, ac.UserID)
	if err != nil {
		return nil, fmt.Errorf("get user: %w", err)
	}
	if user == nil {
		return nil, fmt.Errorf("user not found")
	}
	return &Me{
		User: *userToGraphQL(user),
	}, nil
}

// Vault is the resolver for the vault field.
func (r *queryResolver) Vault(ctx context.Context, id string) (*Vault, error) {
	if err := auth.RequireVaultRole(ctx, id, models.RoleRead); err != nil {
		return nil, err
	}
	v, err := r.vaultService.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	return vaultToGraphQL(v), nil
}

// Vaults is the resolver for the vaults field.
func (r *queryResolver) Vaults(ctx context.Context) ([]*Vault, error) {
	ac, err := auth.FromContext(ctx)
	if err != nil {
		return nil, err
	}
	all, err := r.vaultService.List(ctx)
	if err != nil {
		return nil, err
	}

	// System admin or wildcard → return all vaults
	if ac.IsSystemAdmin {
		result := make([]*Vault, len(all))
		for i := range all {
			result[i] = vaultToGraphQL(&all[i])
		}
		return result, nil
	}

	// Filter to vaults the user has access to
	accessSet := make(map[string]bool, len(ac.Vaults))
	for _, vp := range ac.Vaults {
		if vp.VaultID == auth.WildcardVaultAccess {
			// Wildcard → return all
			result := make([]*Vault, len(all))
			for i := range all {
				result[i] = vaultToGraphQL(&all[i])
			}
			return result, nil
		}
		accessSet[vp.VaultID] = true
	}
	var result []*Vault
	for i := range all {
		id, err := models.RecordIDString(all[i].ID)
		if err != nil {
			slog.Warn("failed to extract vault ID, skipping", "vault_name", all[i].Name, "error", err)
			continue
		}
		if accessSet[id] {
			result = append(result, vaultToGraphQL(&all[i]))
		}
	}
	return result, nil
}

// Document is the resolver for the document field.
func (r *queryResolver) Document(ctx context.Context, vaultID string, path string) (*Document, error) {
	if err := auth.RequireVaultRole(ctx, vaultID, models.RoleRead); err != nil {
		return nil, err
	}
	doc, err := r.db.GetDocumentByPath(ctx, vaultID, path)
	if err != nil {
		return nil, err
	}
	return documentToGraphQL(doc), nil
}

// DocumentByID is the resolver for the documentById field.
func (r *queryResolver) DocumentByID(ctx context.Context, id string) (*Document, error) {
	doc, err := r.db.GetDocumentByID(ctx, id)
	if err != nil {
		return nil, err
	}
	if doc == nil {
		return nil, nil
	}
	vaultID, err := models.RecordIDString(doc.Vault)
	if err != nil {
		return nil, fmt.Errorf("extract vault ID from document: %w", err)
	}
	if err := auth.RequireVaultRole(ctx, vaultID, models.RoleRead); err != nil {
		return nil, err
	}
	return documentToGraphQL(doc), nil
}

// Search is the resolver for the search field.
func (r *queryResolver) Search(ctx context.Context, input SearchInput) ([]*SearchResult, error) {
	if err := auth.RequireVaultRole(ctx, input.VaultID, models.RoleRead); err != nil {
		return nil, err
	}
	limit := 20
	if input.Limit != nil {
		limit = *input.Limit
	}
	results, err := r.searchService.Search(ctx, search.SearchInput{
		VaultID:  input.VaultID,
		Query:    input.Query,
		Labels:   input.Labels,
		DocType:  input.DocType,
		Folder:   input.Folder,
		Limit:    limit,
		BM25Only: true,
	})
	if err != nil {
		return nil, err
	}
	gqlResults := make([]*SearchResult, len(results))
	for i, sr := range results {
		gql := searchResultToGraphQL(sr)
		gqlResults[i] = &gql
	}
	return gqlResults, nil
}

// Template is the resolver for the template field.
func (r *queryResolver) Template(ctx context.Context, id string) (*Template, error) {
	t, err := r.templateService.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	return templateToGraphQL(t), nil
}

// Templates is the resolver for the templates field.
func (r *queryResolver) Templates(ctx context.Context, vaultID *string) ([]*Template, error) {
	if vaultID != nil {
		if err := auth.RequireVaultRole(ctx, *vaultID, models.RoleRead); err != nil {
			return nil, err
		}
	}
	list, err := r.templateService.List(ctx, vaultID)
	if err != nil {
		return nil, err
	}
	result := make([]*Template, len(list))
	for i := range list {
		result[i] = templateToGraphQL(&list[i])
	}
	return result, nil
}

// Conversations is the resolver for the conversations field.
func (r *queryResolver) Conversations(ctx context.Context, vaultID string) ([]*Conversation, error) {
	if err := auth.RequireVaultRole(ctx, vaultID, models.RoleRead); err != nil {
		return nil, err
	}
	ac, err := auth.FromContext(ctx)
	if err != nil {
		return nil, err
	}
	convs, err := r.db.ListConversations(ctx, vaultID, ac.UserID)
	if err != nil {
		return nil, err
	}
	result := make([]*Conversation, len(convs))
	for i := range convs {
		result[i] = conversationToGraphQL(&convs[i])
		result[i].Messages = []*ChatMessage{}
	}
	return result, nil
}

// Conversation is the resolver for the conversation field.
func (r *queryResolver) Conversation(ctx context.Context, id string) (*Conversation, error) {
	conv, err := r.db.GetConversation(ctx, id)
	if err != nil {
		return nil, err
	}
	if conv == nil {
		return nil, nil
	}
	vaultID, err := models.RecordIDString(conv.Vault)
	if err != nil {
		return nil, fmt.Errorf("extract vault ID: %w", err)
	}
	if err := auth.RequireVaultRole(ctx, vaultID, models.RoleRead); err != nil {
		return nil, err
	}
	result := conversationToGraphQL(conv)
	msgs, err := r.db.ListMessages(ctx, id)
	if err != nil {
		return nil, err
	}
	result.Messages = make([]*ChatMessage, len(msgs))
	for i := range msgs {
		result.Messages[i] = messageToGraphQL(&msgs[i])
	}
	return result, nil
}

// VaultMembers is the resolver for the vaultMembers field.
func (r *queryResolver) VaultMembers(ctx context.Context, vaultID string) ([]*VaultMember, error) {
	if err := auth.RequireVaultRole(ctx, vaultID, models.RoleAdmin); err != nil {
		return nil, err
	}
	members, err := r.db.GetVaultMembers(ctx, vaultID)
	if err != nil {
		return nil, err
	}
	result := make([]*VaultMember, 0, len(members))
	for i := range members {
		gql, err := vaultMemberToGraphQL(r.db, ctx, &members[i])
		if err != nil {
			return nil, fmt.Errorf("convert vault member: %w", err)
		}
		result = append(result, gql)
	}
	return result, nil
}

// ShareLinks is the resolver for the shareLinks field.
func (r *queryResolver) ShareLinks(ctx context.Context, vaultID string) ([]*ShareLink, error) {
	if err := auth.RequireVaultRole(ctx, vaultID, models.RoleAdmin); err != nil {
		return nil, err
	}
	links, err := r.db.ListShareLinks(ctx, vaultID)
	if err != nil {
		return nil, err
	}
	result := make([]*ShareLink, len(links))
	for i := range links {
		result[i] = shareLinkToGraphQL(&links[i])
	}
	return result, nil
}

// SyncMetadata is the resolver for the syncMetadata field.
func (r *queryResolver) SyncMetadata(ctx context.Context, vaultID string, since *time.Time, limit *int, offset *int) (*SyncMetadataResult, error) {
	if err := auth.RequireVaultRole(ctx, vaultID, models.RoleRead); err != nil {
		return nil, err
	}

	l := 500
	if limit != nil {
		l = *limit
	}
	o := 0
	if offset != nil {
		o = *offset
	}

	var sinceStr *string
	if since != nil {
		s := since.Format(time.RFC3339Nano)
		sinceStr = &s
	}

	metas, err := r.db.ListSyncMetadata(ctx, vaultID, sinceStr, l, o)
	if err != nil {
		return nil, fmt.Errorf("list sync metadata: %w", err)
	}

	docs := make([]*SyncMeta, len(metas))
	for i, m := range metas {
		docs[i] = syncMetaToGraphQL(m)
	}

	var tombstones []*SyncTombstone
	if since != nil {
		ts, err := r.db.ListTombstones(ctx, vaultID, *sinceStr, l, o)
		if err != nil {
			return nil, fmt.Errorf("list tombstones: %w", err)
		}
		tombstones = make([]*SyncTombstone, len(ts))
		for i, t := range ts {
			tombstones[i] = tombstoneToGraphQL(t)
		}
	}
	if tombstones == nil {
		tombstones = []*SyncTombstone{}
	}

	hasMore := len(metas) >= l

	return &SyncMetadataResult{
		Documents:  docs,
		Tombstones: tombstones,
		HasMore:    hasMore,
	}, nil
}

// ServerConfig is the resolver for the serverConfig field.
func (r *queryResolver) ServerConfig(ctx context.Context) (*ServerConfig, error) {
	r.mu.RLock()
	cfg := r.serverConfig
	r.mu.RUnlock()
	return &cfg, nil
}

// DocumentVersion is the resolver for the documentVersion field.
func (r *queryResolver) DocumentVersion(ctx context.Context, id string) (*DocumentVersion, error) {
	v, err := r.db.GetVersion(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("get version: %w", err)
	}
	if v == nil {
		return nil, nil
	}
	vaultID, err := models.RecordIDString(v.Vault)
	if err != nil {
		return nil, fmt.Errorf("extract vault ID from version: %w", err)
	}
	if err := auth.RequireVaultRole(ctx, vaultID, models.RoleRead); err != nil {
		return nil, err
	}
	return versionToGraphQL(v), nil
}

// DocumentVersions is the resolver for the documentVersions field.
func (r *queryResolver) DocumentVersions(ctx context.Context, documentID string, limit *int, offset *int) (*DocumentVersionConnection, error) {
	doc, err := r.db.GetDocumentByID(ctx, documentID)
	if err != nil {
		return nil, fmt.Errorf("get document: %w", err)
	}
	if doc == nil {
		return nil, fmt.Errorf("document not found: %s", documentID)
	}
	vaultID, err := models.RecordIDString(doc.Vault)
	if err != nil {
		return nil, fmt.Errorf("extract vault ID from document: %w", err)
	}
	if err := auth.RequireVaultRole(ctx, vaultID, models.RoleRead); err != nil {
		return nil, err
	}

	l, o := 20, 0
	if limit != nil {
		l = *limit
	}
	if offset != nil {
		o = *offset
	}
	versions, err := r.db.ListVersions(ctx, documentID, l, o)
	if err != nil {
		return nil, fmt.Errorf("list versions: %w", err)
	}
	count, err := r.db.CountVersions(ctx, documentID)
	if err != nil {
		return nil, fmt.Errorf("count versions: %w", err)
	}
	gqlVersions := make([]*DocumentVersion, len(versions))
	for i := range versions {
		gqlVersions[i] = versionToGraphQL(&versions[i])
	}
	return &DocumentVersionConnection{
		Versions:   gqlVersions,
		TotalCount: count,
	}, nil
}

// VersionDiff is the resolver for the versionDiff field.
func (r *queryResolver) VersionDiff(ctx context.Context, documentID string, fromVersionID *string, toVersionID *string) (*DiffResult, error) {
	doc, err := r.db.GetDocumentByID(ctx, documentID)
	if err != nil {
		return nil, fmt.Errorf("get document: %w", err)
	}
	if doc == nil {
		return nil, fmt.Errorf("document not found: %s", documentID)
	}
	vaultID, err := models.RecordIDString(doc.Vault)
	if err != nil {
		return nil, fmt.Errorf("extract vault ID from document: %w", err)
	}
	if err := auth.RequireVaultRole(ctx, vaultID, models.RoleRead); err != nil {
		return nil, err
	}

	fromContent, err := r.documentService.VersionContent(ctx, documentID, fromVersionID)
	if err != nil {
		return nil, fmt.Errorf("resolve from content: %w", err)
	}
	toContent, err := r.documentService.VersionContent(ctx, documentID, toVersionID)
	if err != nil {
		return nil, fmt.Errorf("resolve to content: %w", err)
	}
	hunks, err := diff.ComputeHunks(fromContent, toContent, 3)
	if err != nil {
		return nil, fmt.Errorf("compute diff: %w", err)
	}
	stats := diff.ComputeStats(hunks)
	gqlHunks := make([]*DiffHunk, len(hunks))
	for i, h := range hunks {
		gqlHunks[i] = hunkToGraphQL(h)
	}
	return &DiffResult{
		Hunks: gqlHunks,
		Stats: &DiffStats{
			Additions:  stats.Additions,
			Deletions:  stats.Deletions,
			HunksCount: stats.HunksCount,
		},
	}, nil
}

// IsSystemAdmin is the resolver for the isSystemAdmin field.
func (r *userResolver) IsSystemAdmin(ctx context.Context, obj *User) (bool, error) {
	user, err := r.db.GetUser(ctx, obj.ID)
	if err != nil {
		return false, fmt.Errorf("get user: %w", err)
	}
	if user == nil {
		return false, nil
	}
	return user.IsSystemAdmin, nil
}

// Labels is the resolver for the labels field.
func (r *vaultResolver) Labels(ctx context.Context, obj *Vault) ([]string, error) {
	return r.db.ListLabels(ctx, obj.ID)
}

// Documents is the resolver for the documents field.
func (r *vaultResolver) Documents(ctx context.Context, obj *Vault, folder *string, labels []string, docType *string) ([]*Document, error) {
	docs, err := r.db.ListDocuments(ctx, db.ListDocumentsFilter{
		VaultID: obj.ID,
		Folder:  folder,
		Labels:  labels,
		DocType: docType,
	})
	if err != nil {
		return nil, err
	}
	result := make([]*Document, len(docs))
	for i := range docs {
		result[i] = documentToGraphQL(&docs[i])
	}
	return result, nil
}

// Folders is the resolver for the folders field.
func (r *vaultResolver) Folders(ctx context.Context, obj *Vault, parent *string) ([]*Folder, error) {
	folders, err := r.vaultService.ListFolders(ctx, obj.ID, parent)
	if err != nil {
		return nil, err
	}
	result := make([]*Folder, len(folders))
	for i := range folders {
		f := folderToGraphQL(folders[i])
		result[i] = &f
	}
	return result, nil
}

// Document returns DocumentResolver implementation.
func (r *Resolver) Document() DocumentResolver { return &documentResolver{r} }

// Me returns MeResolver implementation.
func (r *Resolver) Me() MeResolver { return &meResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

// Vault returns VaultResolver implementation.
func (r *Resolver) Vault() VaultResolver { return &vaultResolver{r} }

type documentResolver struct{ *Resolver }
type meResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
type vaultResolver struct{ *Resolver }
