package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"fmt"
	"log/slog"
	"slices"

	"github.com/raphi011/knowhow/internal/auth"
	"github.com/raphi011/knowhow/internal/db"
	"github.com/raphi011/knowhow/internal/models"
	"github.com/raphi011/knowhow/internal/parser"
	"github.com/raphi011/knowhow/internal/review"
	"github.com/raphi011/knowhow/internal/search"
	surrealmodels "github.com/surrealdb/surrealdb.go/pkg/models"
)

// WikiLinks is the resolver for the wikiLinks field.
func (r *documentResolver) WikiLinks(ctx context.Context, obj *Document) ([]*WikiLink, error) {
	links, err := r.db.GetWikiLinks(ctx, obj.ID)
	if err != nil {
		return nil, err
	}
	result := make([]*WikiLink, len(links))
	for i := range links {
		result[i] = wikiLinkToGraphQL(&links[i])
	}
	return result, nil
}

// Backlinks is the resolver for the backlinks field.
func (r *documentResolver) Backlinks(ctx context.Context, obj *Document) ([]*WikiLink, error) {
	links, err := r.db.GetBacklinks(ctx, obj.ID)
	if err != nil {
		return nil, err
	}
	result := make([]*WikiLink, len(links))
	for i := range links {
		result[i] = wikiLinkToGraphQL(&links[i])
	}
	return result, nil
}

// Relations is the resolver for the relations field.
func (r *documentResolver) Relations(ctx context.Context, obj *Document) ([]*DocRelation, error) {
	relations, err := r.db.GetRelations(ctx, obj.ID)
	if err != nil {
		return nil, err
	}
	result := make([]*DocRelation, len(relations))
	for i := range relations {
		result[i] = relationToGraphQL(&relations[i])
	}
	return result, nil
}

// QueryBlocks is the resolver for the queryBlocks field.
func (r *documentResolver) QueryBlocks(ctx context.Context, obj *Document) ([]*QueryBlock, error) {
	parsed := parser.ExtractQueryBlocks(obj.Content)
	if len(parsed) == 0 {
		return []*QueryBlock{}, nil
	}

	results := make([]*QueryBlock, len(parsed))
	for i, p := range parsed {
		block := resolveQueryBlock(ctx, r.db, obj.VaultID, p)
		results[i] = &block
	}
	return results, nil
}

// Proposals is the resolver for the proposals field.
func (r *documentResolver) Proposals(ctx context.Context, obj *Document, status *ProposalStatus) ([]*DocumentProposal, error) {
	modelStatus := proposalStatusToModel(status)
	proposals, err := r.reviewService.ListForDocument(ctx, obj.ID, modelStatus)
	if err != nil {
		return nil, err
	}
	result := make([]*DocumentProposal, len(proposals))
	for i := range proposals {
		result[i] = proposalToGraphQL(&proposals[i])
	}
	return result, nil
}

// Versions is the resolver for the versions field.
func (r *documentResolver) Versions(ctx context.Context, obj *Document, limit *int, offset *int) (*DocumentVersionConnection, error) {
	l, o := 20, 0
	if limit != nil {
		l = *limit
	}
	if offset != nil {
		o = *offset
	}
	versions, err := r.db.ListVersions(ctx, obj.ID, l, o)
	if err != nil {
		return nil, fmt.Errorf("list versions: %w", err)
	}
	count, err := r.db.CountVersions(ctx, obj.ID)
	if err != nil {
		return nil, fmt.Errorf("count versions: %w", err)
	}
	gqlVersions := make([]*DocumentVersion, len(versions))
	for i := range versions {
		gqlVersions[i] = versionToGraphQL(&versions[i])
	}
	return &DocumentVersionConnection{
		Versions:   gqlVersions,
		TotalCount: count,
	}, nil
}

// Document is the resolver for the document field.
func (r *documentProposalResolver) Document(ctx context.Context, obj *DocumentProposal) (*Document, error) {
	doc, err := r.db.GetDocumentByID(ctx, obj.DocumentID)
	if err != nil {
		return nil, fmt.Errorf("get proposal document: %w", err)
	}
	if doc == nil {
		return nil, fmt.Errorf("proposal document not found: %s", obj.DocumentID)
	}
	vaultID, err := models.RecordIDString(doc.Vault)
	if err != nil {
		return nil, fmt.Errorf("extract vault ID: %w", err)
	}
	if err := auth.RequireVaultAccess(ctx, vaultID); err != nil {
		return nil, err
	}
	return documentToGraphQL(doc), nil
}

// HasConflict is the resolver for the hasConflict field.
func (r *documentProposalResolver) HasConflict(ctx context.Context, obj *DocumentProposal) (bool, error) {
	doc, err := r.db.GetDocumentByID(ctx, obj.DocumentID)
	if err != nil {
		return false, fmt.Errorf("get document: %w", err)
	}
	if doc == nil {
		// Document was deleted — definite conflict
		return true, nil
	}
	currentHash := ""
	if doc.ContentHash != nil {
		currentHash = *doc.ContentHash
	}
	return obj.OriginalHash != "" && currentHash != "" && obj.OriginalHash != currentHash, nil
}

// Diff is the resolver for the diff field.
func (r *documentProposalResolver) Diff(ctx context.Context, obj *DocumentProposal) (*ProposalDiff, error) {
	// Reconstruct the minimal models.DocumentProposal from the GraphQL object
	// to avoid a redundant DB round-trip.
	proposal := &models.DocumentProposal{
		ProposedContent: obj.ProposedContent,
		OriginalHash:    obj.OriginalHash,
		Document:        surrealmodels.RecordID{Table: "document", ID: obj.DocumentID},
	}
	diffResult, err := r.reviewService.Diff(ctx, proposal)
	if err != nil {
		return nil, fmt.Errorf("compute diff: %w", err)
	}
	return diffResultToGraphQL(diffResult), nil
}

// CreateVault is the resolver for the createVault field.
func (r *mutationResolver) CreateVault(ctx context.Context, input VaultInput) (*Vault, error) {
	ac, err := auth.FromContext(ctx)
	if err != nil {
		return nil, err
	}
	v, err := r.vaultService.Create(ctx, ac.UserID, models.VaultInput{
		Name:        input.Name,
		Description: input.Description,
	})
	if err != nil {
		return nil, err
	}
	return vaultToGraphQL(v), nil
}

// DeleteVault is the resolver for the deleteVault field.
func (r *mutationResolver) DeleteVault(ctx context.Context, id string) (bool, error) {
	if err := auth.RequireVaultAccess(ctx, id); err != nil {
		return false, err
	}
	if err := r.vaultService.Delete(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// CreateDocument is the resolver for the createDocument field.
func (r *mutationResolver) CreateDocument(ctx context.Context, vaultID string, file FileInput, source *string) (*Document, error) {
	if err := auth.RequireVaultAccess(ctx, vaultID); err != nil {
		return nil, err
	}
	src := models.SourceManual
	if source != nil {
		src = models.DocumentSource(*source)
		if !src.Valid() {
			return nil, fmt.Errorf("invalid document source: %q", *source)
		}
	}
	doc, err := r.documentService.Create(ctx, models.DocumentInput{
		VaultID: vaultID,
		Path:    file.Path,
		Content: file.Content,
		Source:  src,
	})
	if err != nil {
		return nil, err
	}
	return documentToGraphQL(doc), nil
}

// UpdateDocument is the resolver for the updateDocument field.
func (r *mutationResolver) UpdateDocument(ctx context.Context, vaultID string, path string, content string) (*Document, error) {
	if err := auth.RequireVaultAccess(ctx, vaultID); err != nil {
		return nil, err
	}
	doc, err := r.documentService.Update(ctx, vaultID, path, content)
	if err != nil {
		return nil, err
	}
	return documentToGraphQL(doc), nil
}

// MoveDocument is the resolver for the moveDocument field.
func (r *mutationResolver) MoveDocument(ctx context.Context, vaultID string, oldPath string, newPath string) (*Document, error) {
	if err := auth.RequireVaultAccess(ctx, vaultID); err != nil {
		return nil, err
	}
	doc, err := r.documentService.Move(ctx, vaultID, oldPath, newPath)
	if err != nil {
		return nil, err
	}
	return documentToGraphQL(doc), nil
}

// DeleteDocument is the resolver for the deleteDocument field.
func (r *mutationResolver) DeleteDocument(ctx context.Context, vaultID string, path string) (bool, error) {
	if err := auth.RequireVaultAccess(ctx, vaultID); err != nil {
		return false, err
	}
	if err := r.documentService.Delete(ctx, vaultID, path); err != nil {
		return false, err
	}
	return true, nil
}

// DeleteDocumentsByPrefix is the resolver for the deleteDocumentsByPrefix field.
func (r *mutationResolver) DeleteDocumentsByPrefix(ctx context.Context, vaultID string, pathPrefix string) (int, error) {
	if err := auth.RequireVaultAccess(ctx, vaultID); err != nil {
		return 0, err
	}
	return r.documentService.DeleteByPrefix(ctx, vaultID, pathPrefix)
}

// MoveDocumentsByPrefix is the resolver for the moveDocumentsByPrefix field.
func (r *mutationResolver) MoveDocumentsByPrefix(ctx context.Context, vaultID string, oldPrefix string, newPrefix string) (int, error) {
	if err := auth.RequireVaultAccess(ctx, vaultID); err != nil {
		return 0, err
	}
	return r.documentService.MoveByPrefix(ctx, vaultID, oldPrefix, newPrefix)
}

// CreateRelation is the resolver for the createRelation field.
func (r *mutationResolver) CreateRelation(ctx context.Context, input RelationInput) (*DocRelation, error) {
	// Verify access to both documents' vaults
	fromDoc, err := r.db.GetDocumentByID(ctx, input.FromDocID)
	if err != nil {
		return nil, fmt.Errorf("get from document: %w", err)
	}
	if fromDoc == nil {
		return nil, fmt.Errorf("from document not found: %s", input.FromDocID)
	}
	fromVaultID, err := models.RecordIDString(fromDoc.Vault)
	if err != nil {
		return nil, fmt.Errorf("extract from document vault ID: %w", err)
	}
	if err := auth.RequireVaultAccess(ctx, fromVaultID); err != nil {
		return nil, err
	}

	toDoc, err := r.db.GetDocumentByID(ctx, input.ToDocID)
	if err != nil {
		return nil, fmt.Errorf("get to document: %w", err)
	}
	if toDoc == nil {
		return nil, fmt.Errorf("to document not found: %s", input.ToDocID)
	}
	toVaultID, err := models.RecordIDString(toDoc.Vault)
	if err != nil {
		return nil, fmt.Errorf("extract to document vault ID: %w", err)
	}
	if err := auth.RequireVaultAccess(ctx, toVaultID); err != nil {
		return nil, err
	}

	rel, err := r.db.CreateRelation(ctx, models.DocRelationInput{
		FromDocID: input.FromDocID,
		ToDocID:   input.ToDocID,
		RelType:   input.RelType,
		Source:    string(models.RelSourceAPI),
	})
	if err != nil {
		return nil, err
	}
	return relationToGraphQL(rel), nil
}

// DeleteRelation is the resolver for the deleteRelation field.
func (r *mutationResolver) DeleteRelation(ctx context.Context, id string) (bool, error) {
	// Look up the relation to verify vault access on both documents
	relations, err := r.db.GetRelationByID(ctx, id)
	if err != nil {
		return false, fmt.Errorf("get relation: %w", err)
	}
	if relations == nil {
		return false, fmt.Errorf("relation not found: %s", id)
	}
	inDocID, err := models.RecordIDString(relations.In)
	if err != nil {
		return false, fmt.Errorf("extract relation in doc ID: %w", err)
	}
	inDoc, err := r.db.GetDocumentByID(ctx, inDocID)
	if err != nil {
		return false, fmt.Errorf("get in document: %w", err)
	}
	if inDoc != nil {
		vaultID, err := models.RecordIDString(inDoc.Vault)
		if err != nil {
			return false, fmt.Errorf("extract vault ID: %w", err)
		}
		if err := auth.RequireVaultAccess(ctx, vaultID); err != nil {
			return false, err
		}
	}

	if err := r.db.DeleteRelation(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// CreateTemplate is the resolver for the createTemplate field.
func (r *mutationResolver) CreateTemplate(ctx context.Context, input TemplateInput) (*Template, error) {
	if input.VaultID != nil {
		if err := auth.RequireVaultAccess(ctx, *input.VaultID); err != nil {
			return nil, err
		}
	}
	isAI := false
	if input.IsAITemplate != nil {
		isAI = *input.IsAITemplate
	}
	t, err := r.templateService.Create(ctx, models.TemplateInput{
		VaultID:      input.VaultID,
		Name:         input.Name,
		Description:  input.Description,
		Content:      input.Content,
		IsAITemplate: isAI,
	})
	if err != nil {
		return nil, err
	}
	return templateToGraphQL(t), nil
}

// DeleteTemplate is the resolver for the deleteTemplate field.
func (r *mutationResolver) DeleteTemplate(ctx context.Context, id string) (bool, error) {
	// Check vault access if the template is scoped to a vault
	tmpl, err := r.templateService.Get(ctx, id)
	if err != nil {
		return false, fmt.Errorf("get template: %w", err)
	}
	if tmpl == nil {
		return false, fmt.Errorf("template not found: %s", id)
	}
	if tmpl.Vault != nil {
		vaultID, err := models.RecordIDString(*tmpl.Vault)
		if err != nil {
			return false, fmt.Errorf("extract template vault ID: %w", err)
		}
		if err := auth.RequireVaultAccess(ctx, vaultID); err != nil {
			return false, err
		}
	}

	if err := r.templateService.Delete(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// ProposeDocumentUpdate is the resolver for the proposeDocumentUpdate field.
func (r *mutationResolver) ProposeDocumentUpdate(ctx context.Context, input ProposeDocumentUpdateInput) (*DocumentProposal, error) {
	if err := auth.RequireVaultAccess(ctx, input.VaultID); err != nil {
		return nil, err
	}
	source := proposalSourceToModel(input.Source)
	proposal, err := r.reviewService.CreateByPath(ctx, input.VaultID, input.Path, input.ProposedContent, input.Description, source)
	if err != nil {
		return nil, err
	}
	return proposalToGraphQL(proposal), nil
}

// ApproveProposal is the resolver for the approveProposal field.
func (r *mutationResolver) ApproveProposal(ctx context.Context, id string, notes *string) (*Document, error) {
	proposal, err := r.reviewService.Get(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("get proposal: %w", err)
	}
	if proposal == nil {
		return nil, fmt.Errorf("proposal not found: %s", id)
	}
	vaultID, err := models.RecordIDString(proposal.Vault)
	if err != nil {
		return nil, fmt.Errorf("extract vault ID: %w", err)
	}
	if err := auth.RequireVaultAccess(ctx, vaultID); err != nil {
		return nil, err
	}
	doc, err := r.reviewService.ApproveAll(ctx, id, notes)
	if err != nil {
		return nil, err
	}
	return documentToGraphQL(doc), nil
}

// ApproveProposalHunks is the resolver for the approveProposalHunks field.
func (r *mutationResolver) ApproveProposalHunks(ctx context.Context, input ApproveHunksInput) (*Document, error) {
	proposal, err := r.reviewService.Get(ctx, input.ProposalID)
	if err != nil {
		return nil, fmt.Errorf("get proposal: %w", err)
	}
	if proposal == nil {
		return nil, fmt.Errorf("proposal not found: %s", input.ProposalID)
	}
	vaultID, err := models.RecordIDString(proposal.Vault)
	if err != nil {
		return nil, fmt.Errorf("extract vault ID: %w", err)
	}
	if err := auth.RequireVaultAccess(ctx, vaultID); err != nil {
		return nil, err
	}
	doc, err := r.reviewService.ApproveHunks(ctx, input.ProposalID, input.HunkIndexes, input.Notes)
	if err != nil {
		return nil, err
	}
	return documentToGraphQL(doc), nil
}

// RejectProposal is the resolver for the rejectProposal field.
func (r *mutationResolver) RejectProposal(ctx context.Context, id string, notes *string) (bool, error) {
	proposal, err := r.reviewService.Get(ctx, id)
	if err != nil {
		return false, fmt.Errorf("get proposal: %w", err)
	}
	if proposal == nil {
		return false, fmt.Errorf("proposal not found: %s", id)
	}
	vaultID, err := models.RecordIDString(proposal.Vault)
	if err != nil {
		return false, fmt.Errorf("extract vault ID: %w", err)
	}
	if err := auth.RequireVaultAccess(ctx, vaultID); err != nil {
		return false, err
	}
	if err := r.reviewService.Reject(ctx, id, notes); err != nil {
		return false, err
	}
	return true, nil
}

// CreateFolder is the resolver for the createFolder field.
func (r *mutationResolver) CreateFolder(ctx context.Context, vaultID string, path string) (*Folder, error) {
	if err := auth.RequireVaultAccess(ctx, vaultID); err != nil {
		return nil, err
	}
	folder, err := r.vaultService.CreateFolder(ctx, vaultID, path)
	if err != nil {
		return nil, err
	}
	f := folderToGraphQL(*folder)
	return &f, nil
}

// DeleteFolder is the resolver for the deleteFolder field.
func (r *mutationResolver) DeleteFolder(ctx context.Context, vaultID string, path string) (bool, error) {
	if err := auth.RequireVaultAccess(ctx, vaultID); err != nil {
		return false, err
	}
	if err := r.vaultService.DeleteFolder(ctx, vaultID, path); err != nil {
		return false, err
	}
	return true, nil
}

// MoveFolder is the resolver for the moveFolder field.
func (r *mutationResolver) MoveFolder(ctx context.Context, vaultID string, oldPath string, newPath string) (bool, error) {
	if err := auth.RequireVaultAccess(ctx, vaultID); err != nil {
		return false, err
	}
	if err := r.vaultService.MoveFolder(ctx, vaultID, oldPath, newPath); err != nil {
		return false, err
	}
	return true, nil
}

// CreateConversation is the resolver for the createConversation field.
func (r *mutationResolver) CreateConversation(ctx context.Context, vaultID string) (*Conversation, error) {
	if err := auth.RequireVaultAccess(ctx, vaultID); err != nil {
		return nil, err
	}
	ac, err := auth.FromContext(ctx)
	if err != nil {
		return nil, err
	}
	conv, err := r.db.CreateConversation(ctx, vaultID, ac.UserID)
	if err != nil {
		return nil, err
	}
	result := conversationToGraphQL(conv)
	result.Messages = []*ChatMessage{}
	return result, nil
}

// DeleteConversation is the resolver for the deleteConversation field.
func (r *mutationResolver) DeleteConversation(ctx context.Context, id string) (bool, error) {
	conv, err := r.db.GetConversation(ctx, id)
	if err != nil {
		return false, err
	}
	if conv == nil {
		return false, fmt.Errorf("conversation not found")
	}
	vaultID, err := models.RecordIDString(conv.Vault)
	if err != nil {
		return false, fmt.Errorf("extract vault ID: %w", err)
	}
	if err := auth.RequireVaultAccess(ctx, vaultID); err != nil {
		return false, err
	}
	if err := r.db.DeleteConversation(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// RenameConversation is the resolver for the renameConversation field.
func (r *mutationResolver) RenameConversation(ctx context.Context, id string, title string) (*Conversation, error) {
	conv, err := r.db.GetConversation(ctx, id)
	if err != nil {
		return nil, err
	}
	if conv == nil {
		return nil, fmt.Errorf("conversation not found")
	}
	vaultID, err := models.RecordIDString(conv.Vault)
	if err != nil {
		return nil, fmt.Errorf("extract vault ID: %w", err)
	}
	if err := auth.RequireVaultAccess(ctx, vaultID); err != nil {
		return nil, err
	}
	if err := r.db.UpdateConversationTitle(ctx, id, title); err != nil {
		return nil, err
	}
	updated, err := r.db.GetConversation(ctx, id)
	if err != nil {
		return nil, err
	}
	result := conversationToGraphQL(updated)
	result.Messages = []*ChatMessage{}
	return result, nil
}

// RollbackDocument is the resolver for the rollbackDocument field.
func (r *mutationResolver) RollbackDocument(ctx context.Context, vaultID string, documentID string, versionID string) (*Document, error) {
	if err := auth.RequireVaultAccess(ctx, vaultID); err != nil {
		return nil, err
	}
	doc, err := r.documentService.Rollback(ctx, vaultID, documentID, versionID)
	if err != nil {
		return nil, fmt.Errorf("rollback document: %w", err)
	}
	return documentToGraphQL(doc), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*Me, error) {
	ac, err := auth.FromContext(ctx)
	if err != nil {
		return nil, err
	}
	user, err := r.db.GetUser(ctx, ac.UserID)
	if err != nil {
		return nil, fmt.Errorf("get user: %w", err)
	}
	if user == nil {
		return nil, fmt.Errorf("user not found")
	}
	return &Me{
		User:        *userToGraphQL(user),
		VaultAccess: ac.VaultAccess,
	}, nil
}

// Vault is the resolver for the vault field.
func (r *queryResolver) Vault(ctx context.Context, id string) (*Vault, error) {
	if err := auth.RequireVaultAccess(ctx, id); err != nil {
		return nil, err
	}
	v, err := r.vaultService.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	return vaultToGraphQL(v), nil
}

// Vaults is the resolver for the vaults field.
func (r *queryResolver) Vaults(ctx context.Context) ([]*Vault, error) {
	ac, err := auth.FromContext(ctx)
	if err != nil {
		return nil, err
	}
	all, err := r.vaultService.List(ctx)
	if err != nil {
		return nil, err
	}
	// Wildcard grants access to all vaults (no-auth mode)
	hasWildcard := slices.Contains(ac.VaultAccess, auth.WildcardVaultAccess)

	// Filter to vaults the user has access to
	accessSet := make(map[string]bool, len(ac.VaultAccess))
	for _, id := range ac.VaultAccess {
		accessSet[id] = true
	}
	var result []*Vault
	for i := range all {
		if hasWildcard {
			result = append(result, vaultToGraphQL(&all[i]))
			continue
		}
		id, err := models.RecordIDString(all[i].ID)
		if err != nil {
			slog.Warn("failed to extract vault ID, skipping", "vault_name", all[i].Name, "error", err)
			continue
		}
		if accessSet[id] {
			result = append(result, vaultToGraphQL(&all[i]))
		}
	}
	return result, nil
}

// Document is the resolver for the document field.
func (r *queryResolver) Document(ctx context.Context, vaultID string, path string) (*Document, error) {
	if err := auth.RequireVaultAccess(ctx, vaultID); err != nil {
		return nil, err
	}
	doc, err := r.db.GetDocumentByPath(ctx, vaultID, path)
	if err != nil {
		return nil, err
	}
	return documentToGraphQL(doc), nil
}

// DocumentByID is the resolver for the documentById field.
func (r *queryResolver) DocumentByID(ctx context.Context, id string) (*Document, error) {
	doc, err := r.db.GetDocumentByID(ctx, id)
	if err != nil {
		return nil, err
	}
	if doc == nil {
		return nil, nil
	}
	vaultID, err := models.RecordIDString(doc.Vault)
	if err != nil {
		return nil, fmt.Errorf("extract vault ID from document: %w", err)
	}
	if err := auth.RequireVaultAccess(ctx, vaultID); err != nil {
		return nil, err
	}
	return documentToGraphQL(doc), nil
}

// Search is the resolver for the search field.
func (r *queryResolver) Search(ctx context.Context, input SearchInput) ([]*SearchResult, error) {
	if err := auth.RequireVaultAccess(ctx, input.VaultID); err != nil {
		return nil, err
	}
	limit := 20
	if input.Limit != nil {
		limit = *input.Limit
	}
	results, err := r.searchService.Search(ctx, search.SearchInput{
		VaultID:  input.VaultID,
		Query:    input.Query,
		Labels:   input.Labels,
		DocType:  input.DocType,
		Folder:   input.Folder,
		Limit:    limit,
		BM25Only: true,
	})
	if err != nil {
		return nil, err
	}
	gqlResults := make([]*SearchResult, len(results))
	for i, sr := range results {
		gql := searchResultToGraphQL(sr)
		gqlResults[i] = &gql
	}
	return gqlResults, nil
}

// Template is the resolver for the template field.
func (r *queryResolver) Template(ctx context.Context, id string) (*Template, error) {
	t, err := r.templateService.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	return templateToGraphQL(t), nil
}

// Templates is the resolver for the templates field.
func (r *queryResolver) Templates(ctx context.Context, vaultID *string) ([]*Template, error) {
	if vaultID != nil {
		if err := auth.RequireVaultAccess(ctx, *vaultID); err != nil {
			return nil, err
		}
	}
	list, err := r.templateService.List(ctx, vaultID)
	if err != nil {
		return nil, err
	}
	result := make([]*Template, len(list))
	for i := range list {
		result[i] = templateToGraphQL(&list[i])
	}
	return result, nil
}

// Proposal is the resolver for the proposal field.
func (r *queryResolver) Proposal(ctx context.Context, id string) (*DocumentProposal, error) {
	proposal, err := r.reviewService.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	if proposal == nil {
		return nil, nil
	}
	vaultID, err := models.RecordIDString(proposal.Vault)
	if err != nil {
		return nil, fmt.Errorf("extract vault ID: %w", err)
	}
	if err := auth.RequireVaultAccess(ctx, vaultID); err != nil {
		return nil, err
	}
	return proposalToGraphQL(proposal), nil
}

// Proposals is the resolver for the proposals field.
func (r *queryResolver) Proposals(ctx context.Context, vaultID string, status *ProposalStatus) ([]*DocumentProposal, error) {
	if err := auth.RequireVaultAccess(ctx, vaultID); err != nil {
		return nil, err
	}
	modelStatus := proposalStatusToModel(status)
	proposals, err := r.reviewService.List(ctx, vaultID, modelStatus)
	if err != nil {
		return nil, err
	}
	result := make([]*DocumentProposal, len(proposals))
	for i := range proposals {
		result[i] = proposalToGraphQL(&proposals[i])
	}
	return result, nil
}

// Conversations is the resolver for the conversations field.
func (r *queryResolver) Conversations(ctx context.Context, vaultID string) ([]*Conversation, error) {
	if err := auth.RequireVaultAccess(ctx, vaultID); err != nil {
		return nil, err
	}
	ac, err := auth.FromContext(ctx)
	if err != nil {
		return nil, err
	}
	convs, err := r.db.ListConversations(ctx, vaultID, ac.UserID)
	if err != nil {
		return nil, err
	}
	result := make([]*Conversation, len(convs))
	for i := range convs {
		result[i] = conversationToGraphQL(&convs[i])
		result[i].Messages = []*ChatMessage{}
	}
	return result, nil
}

// Conversation is the resolver for the conversation field.
func (r *queryResolver) Conversation(ctx context.Context, id string) (*Conversation, error) {
	conv, err := r.db.GetConversation(ctx, id)
	if err != nil {
		return nil, err
	}
	if conv == nil {
		return nil, nil
	}
	vaultID, err := models.RecordIDString(conv.Vault)
	if err != nil {
		return nil, fmt.Errorf("extract vault ID: %w", err)
	}
	if err := auth.RequireVaultAccess(ctx, vaultID); err != nil {
		return nil, err
	}
	result := conversationToGraphQL(conv)
	msgs, err := r.db.ListMessages(ctx, id)
	if err != nil {
		return nil, err
	}
	result.Messages = make([]*ChatMessage, len(msgs))
	for i := range msgs {
		result.Messages[i] = messageToGraphQL(&msgs[i])
	}
	return result, nil
}

// ServerConfig is the resolver for the serverConfig field.
func (r *queryResolver) ServerConfig(ctx context.Context) (*ServerConfig, error) {
	return &r.serverConfig, nil
}

// DocumentVersion is the resolver for the documentVersion field.
func (r *queryResolver) DocumentVersion(ctx context.Context, id string) (*DocumentVersion, error) {
	v, err := r.db.GetVersion(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("get version: %w", err)
	}
	if v == nil {
		return nil, nil
	}
	vaultID, err := models.RecordIDString(v.Vault)
	if err != nil {
		return nil, fmt.Errorf("extract vault ID from version: %w", err)
	}
	if err := auth.RequireVaultAccess(ctx, vaultID); err != nil {
		return nil, err
	}
	return versionToGraphQL(v), nil
}

// DocumentVersions is the resolver for the documentVersions field.
func (r *queryResolver) DocumentVersions(ctx context.Context, documentID string, limit *int, offset *int) (*DocumentVersionConnection, error) {
	doc, err := r.db.GetDocumentByID(ctx, documentID)
	if err != nil {
		return nil, fmt.Errorf("get document: %w", err)
	}
	if doc == nil {
		return nil, fmt.Errorf("document not found: %s", documentID)
	}
	vaultID, err := models.RecordIDString(doc.Vault)
	if err != nil {
		return nil, fmt.Errorf("extract vault ID from document: %w", err)
	}
	if err := auth.RequireVaultAccess(ctx, vaultID); err != nil {
		return nil, err
	}

	l, o := 20, 0
	if limit != nil {
		l = *limit
	}
	if offset != nil {
		o = *offset
	}
	versions, err := r.db.ListVersions(ctx, documentID, l, o)
	if err != nil {
		return nil, fmt.Errorf("list versions: %w", err)
	}
	count, err := r.db.CountVersions(ctx, documentID)
	if err != nil {
		return nil, fmt.Errorf("count versions: %w", err)
	}
	gqlVersions := make([]*DocumentVersion, len(versions))
	for i := range versions {
		gqlVersions[i] = versionToGraphQL(&versions[i])
	}
	return &DocumentVersionConnection{
		Versions:   gqlVersions,
		TotalCount: count,
	}, nil
}

// VersionDiff is the resolver for the versionDiff field.
func (r *queryResolver) VersionDiff(ctx context.Context, documentID string, fromVersionID *string, toVersionID *string) (*ProposalDiff, error) {
	doc, err := r.db.GetDocumentByID(ctx, documentID)
	if err != nil {
		return nil, fmt.Errorf("get document: %w", err)
	}
	if doc == nil {
		return nil, fmt.Errorf("document not found: %s", documentID)
	}
	vaultID, err := models.RecordIDString(doc.Vault)
	if err != nil {
		return nil, fmt.Errorf("extract vault ID from document: %w", err)
	}
	if err := auth.RequireVaultAccess(ctx, vaultID); err != nil {
		return nil, err
	}

	fromContent, err := r.documentService.VersionContent(ctx, documentID, fromVersionID)
	if err != nil {
		return nil, fmt.Errorf("resolve from content: %w", err)
	}
	toContent, err := r.documentService.VersionContent(ctx, documentID, toVersionID)
	if err != nil {
		return nil, fmt.Errorf("resolve to content: %w", err)
	}
	hunks, err := review.ComputeHunks(fromContent, toContent, 3)
	if err != nil {
		return nil, fmt.Errorf("compute diff: %w", err)
	}
	stats := review.ComputeStats(hunks)
	gqlHunks := make([]*DiffHunk, len(hunks))
	for i, h := range hunks {
		gqlHunks[i] = hunkToGraphQL(h)
	}
	return &ProposalDiff{
		Hunks:       gqlHunks,
		HasConflict: false,
		Stats: &DiffStats{
			Additions:  stats.Additions,
			Deletions:  stats.Deletions,
			HunksCount: stats.HunksCount,
		},
	}, nil
}

// Labels is the resolver for the labels field.
func (r *vaultResolver) Labels(ctx context.Context, obj *Vault) ([]string, error) {
	return r.db.ListLabels(ctx, obj.ID)
}

// Documents is the resolver for the documents field.
func (r *vaultResolver) Documents(ctx context.Context, obj *Vault, folder *string, labels []string, docType *string) ([]*Document, error) {
	docs, err := r.db.ListDocuments(ctx, db.ListDocumentsFilter{
		VaultID: obj.ID,
		Folder:  folder,
		Labels:  labels,
		DocType: docType,
	})
	if err != nil {
		return nil, err
	}
	result := make([]*Document, len(docs))
	for i := range docs {
		result[i] = documentToGraphQL(&docs[i])
	}
	return result, nil
}

// Folders is the resolver for the folders field.
func (r *vaultResolver) Folders(ctx context.Context, obj *Vault, parent *string) ([]*Folder, error) {
	folders, err := r.vaultService.ListFolders(ctx, obj.ID, parent)
	if err != nil {
		return nil, err
	}
	result := make([]*Folder, len(folders))
	for i := range folders {
		f := folderToGraphQL(folders[i])
		result[i] = &f
	}
	return result, nil
}

// Document returns DocumentResolver implementation.
func (r *Resolver) Document() DocumentResolver { return &documentResolver{r} }

// DocumentProposal returns DocumentProposalResolver implementation.
func (r *Resolver) DocumentProposal() DocumentProposalResolver { return &documentProposalResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Vault returns VaultResolver implementation.
func (r *Resolver) Vault() VaultResolver { return &vaultResolver{r} }

type documentResolver struct{ *Resolver }
type documentProposalResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type vaultResolver struct{ *Resolver }
